### ISSUE TITLE
App crashes trying to download maps when there is no internet connection

### ISSUE THREAD

**Issue by ReyhanJB** [openbmap/radiocells-scanner-android#179]
What steps will reproduce the problem? Disconnect wifi and cellular network. Try to download offline maps. 

What is the expected output? What do you see instead? The app should gives an error that there is no active internet connection. Instead, it crashes. 

What version are you using? On what operating system?
Latest version downloaded from Github, running on Nexus 6 (Doze disabled)

Please provide any additional information below.

`01-16 16:55:59.734 3586-3586/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: org.openbmap, PID: 3586
                                                 java.lang.NullPointerException: Attempt to read from field 'java.lang.String org.openbmap.activities.DialogPreferenceMapsGroup.string' on a null object reference
                                                     at org.openbmap.activities.DialogPreferenceMapsListAdapter.getGroupView(DialogPreferenceMapsListAdapter.java:117)
                                                     at android.widget.ExpandableListConnector.getView(ExpandableListConnector.java:446)
                                                     at android.widget.AbsListView.obtainView(AbsListView.java:2346)
                                                     at android.widget.ListView.measureHeightOfChildren(ListView.java:1281)
                                                     at android.widget.ListView.onMeasure(ListView.java:1188)
                                                     at android.view.View.measure(View.java:18794)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                     at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1112)
                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:632)
                                                     at android.view.View.measure(View.java:18794)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                     at android.view.View.measure(View.java:18794)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                     at android.view.View.measure(View.java:18794)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                     at android.view.View.measure(View.java:18794)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                     at android.view.View.measure(View.java:18794)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                     at android.view.View.measure(View.java:18794)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                     at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
                                                     at android.view.View.measure(View.java:18794)
                                                     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
                                                     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1191)
                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                     at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by wish7code** [comment]
Can reproduce.. Thanks for reporting..

**Comment by wish7code** [comment]
Fixed in upcoming release with 47d2c706b62fc
