### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by eileenfan** [openbmap/radiocells-scanner-android#207]
//package name: org.openbmap
//version: 0.8.15
 java.lang.StringIndexOutOfBoundsException: length=0; regionStart=0; regionLength=-1
 	at java.lang.String.startEndAndLength(String.java:583)
 	at java.lang.String.substring(String.java:1464)
 	at org.openbmap.utils.p.onClick(Unknown Source)
 	at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:941)
 	at android.widget.AdapterView.performItemClick(AdapterView.java:298)
 	at android.widget.AbsListView.performItemClick(AbsListView.java:1100)
 	at android.widget.AbsListView.onKeyUp(AbsListView.java:2929)
 	at android.widget.ListView.commonKey(ListView.java:2267)
 	at android.widget.ListView.onKeyUp(ListView.java:2122)
 	at android.view.KeyEvent.dispatch(KeyEvent.java:2647)
 	at android.view.View.dispatchKeyEvent(View.java:7343)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1388)
 	at android.widget.ListView.dispatchKeyEvent(ListView.java:2097)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:1933)
 	at com.android.internal.policy.impl.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1408)
 	at android.app.Dialog.dispatchKeyEvent(Dialog.java:706)
 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1860)
 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:3791)
 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3774)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3483)
 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3540)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3483)
 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3540)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3483)
 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3540)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5419)
 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5399)
 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5370)

**Comment by wish7code** [comment]
Hard to say where this comes from:

**org.openbmap.utils.p.onClick**

Actually there's no such class in 0.8.15 client.

Are you maybe using a modified client?
